### ISSUE TITLE
Problemas al posicionar la imagen

### ISSUE THREAD

**Issue by LuksFay** [LuksFay/Haircare---Prueba#1]
Debe haber algo en esta parte de css

```css
.for{
    display: flex;
}
.c1{
    width: 719px;
    height: 571px;
}
.fm_img{
    background: url(formen.jpg);
    width: 719px;
    height: 571px;
    filter: brightness(40%);
    position: absolute;
}
.a{
    position: relative;
    text-align: center;
}
.a p{
    color: #fff;
}

```

o esta parte de html

```html
    <section id="for">
        <div class="columnas">
            <div class="c1">
                <div class="fm_img"></div>
                <div class="a">
                    <p>For Men</p>
                    <a href="">See pricing</a>
                </div>
            </div>
        </div>
    </section>
```

que me posiciona mal la imagen, quizas el problama esta en
```html
<header>
```

SOLUCIONADO

```css
    background: url(bg-2.jpg);
    background-position: top;
    width: 100%;
   - height: 100%;
   + height: 877px;
    filter: brightness(40%);
    position: absolute;
}
```
el problema estaba en
```html
<header>
```
